### ISSUE TITLE
Add contributing.md file

### ISSUE THREAD

**Issue by erikvold** [iarna/require-inject#8]
It'd be nice to see a contributing file :) https://github.com/blog/1184-contributing-guidelines

**Comment by iarna** [comment]
I would take one as a PR. ;)

But seriously, I would. It's a fine idea, I'm just not sure when I'd have a spare moment to write one. The only biggy is that changes should include a test. (And all tests must pass, hopefully obviously. =D)

I'll probably add `standard` to the `npm test` run sometime too.

**Comment by erikvold** [comment]
> I'll probably add `standard` to the `npm test` run sometime too. (Edit: I've added standard, so now tests fail if your source code formatting is off. Progress!)

Awesome!

**Comment by iarna** [comment]
Contrib docs (and my general module template) landed!
